name: Generate F-Droid repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: "45 2 * * *"

jobs:
  apps:
    name: "Generate repo from apps listing"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create basic directory structure
        run: mkdir -p fdroid/repo

      - name: Restore correct mtime
        run: |
          sudo apt install git-restore-mtime 
          git restore-mtime

      - name: Install F-Droid server software
        run: |
         sudo add-apt-repository ppa:fdroid/fdroidserver
         sudo apt-get update
         sudo apt-get install fdroidserver

      - name: Set up repo secrets
        run: |
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 -d - > fdroid/keystore.p12
          echo "${{ secrets.CONFIG_YML }}" | base64 -d - > fdroid/config.yml

      - uses: actions/setup-go@v2
        name: Set up Go
        with:
          go-version: '^1.17.0' 
        
      - name: Run update script
        run: bash update.sh 2>&1
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Push dir to Git
        uses: iziwl/git-push-action@v1.0.4
        with:
    # Username of token holder
          git_token_holder: xrz-cloud
    # Token for the destination repo. Can be passed in using $\{{ secrets.GIT_TOKEN }}
          git_token: ${{ secrets.GH_ACCESS_TOKEN }}
    # Repository URL after "https://", like "github.com/USER_NAME/REPO_NAME.git"
          repository_url: github.com/xrz-cloud/Download2MyFrdoid.git
    # Directory to push
          push_dir: ./
    # User to commit
          commit_user: github-actions
    # Email of the user to commit
          commit_email: 62951481+github-actions[bot]@users.noreply.github.com
    # Destination branch to push changes
          branch: main
    # Commit messgae
          commit_message: 'Automated update'
